version: '3.1' 
services:
  csgo-practice1:
    image: csgo-practice:v1
    environment:
      - LGSM_GAMESERVERNAME=csgoserver
      - LGSM_IP=00.00.000.000
      - LGSM_UPDATEINSTALLSKIP=UPDATE
      - LGSM_PORT=27085
      - LGSM_DEFAULTMAP=de_overpass
      - LGSM_GAMETYPE=0
      - LGSM_GAMEMODE=1
      - LGSM_MAPGROUP=mg_active
      - LGSM_TICKRATE=128
      - LGSM_MAXPLAYERS=12
      - LGSM_GSLT=<GSLT TOKEN>
    volumes:
      - "/home/container/csgo-practice1/data/logs:/home/steam/linuxgsm/logs"
      - "/home/container/csgo-practice1/data/serverfiles:/home/steam/linuxgsm/serverfiles/"
    ports:
      - "27075:27075/tcp"
      - "27085:27085/tcp"
      - "27086:27086/tcp"
      - "27075:27075/udp"
      - "27085:27085/udp"
      - "27086:27086/udp"

